---
- name: Create user account - Kris
  user:
    comment: Kristopher Newman
    name: kris
    password: "{{ kris_pw_hash }}"
    append: yes
    groups:
     - sudo
     - adm
     - cdrom
     - sudo
     - dip
     - plugdev
     - lpadmin
     - sambashare
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/kris
  tags:
    - useradd
    - kris
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Create user account - Plex
  user:
    comment: Plex User
    name: plex
    password: "{{ plex_pw_hash }}"
    append: yes
    groups:
      - cdrom
      - dip
      - plugdev
      - lpadmin
      - sambashare
      - media_access
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/plex
  tags:
    - useradd
    - plex
  when: "'plex' in group_names"

- name: Create user account - pihole
  user:
    comment: "Pihole NoLogin user"
    name: pihole
    append: yes
    groups:
     - www-data
    state: present
    shell: /sbin/nologin
    system: no
    createhome: yes
    uid: 999
  tags:
    - useradd
    - pihole
  when: "'pihole_vm' in group_names"

- name: Add Kris user to the sudoers
  copy:
    dest: "/etc/sudoers.d/kris"
    content: "kris  ALL=(ALL)  NOPASSWD: ALL"
  tags:
    - sudo
    - kris
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Deploy SSH key for kris
  authorized_key:
    user: kris
    state: present
    key: "{{ lookup('file', 'kris_public_key') }}"
  tags:
    - ssh
    - kris
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - inventory_hostname != "titanium"

- name: Create .ssh directory for kris
  file:
    path: /home/jarvis/.ssh
    state: directory
    owner: kris
    group: kris
    mode: '0700'
  tags:
    - ssh
    - kris
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - inventory_hostname == "titanium"

- name: Create .ssh directory for jarvis
  file:
    path: /home/jarvis/.ssh
    state: directory
    owner: jarvis
    group: jarvis
    mode: '0700'
  tags:
    - ssh
    - jarvis
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - inventory_hostname == "titanium"

- name: Install public key for jarvis
  copy:
    content: '{{ jarvis_ssl_certificate }}'
    dest: /home/jarvis/.ssh/id_rsa.pub
    owner: jarvis
    group: jarvis
    mode: 0644
  tags:
    - ssh
    - jarvis
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - inventory_hostname == "titanium"

- name: Install private key for jarvis
  copy:
    content: '{{ jarvis_ssl_private_key }}'
    dest: /home/jarvis/.ssh/id_rsa
    owner: jarvis
    group: jarvis
    mode: 0600
  no_log: true
  tags:
    - ssh
    - jarvis
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - inventory_hostname == "titanium"

- name: Install public key for kris
  copy:
    content: '{{ kris_ssl_certificate }}'
    dest: /home/kris/.ssh/id_rsa.pub
    owner: kris
    group: kris
    mode: 0644
  tags:
    - ssh
    - kris
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - inventory_hostname == "titanium"

- name: Install private key for kris
  copy:
    content: '{{ kris_ssl_private_key }}'
    dest: /home/kris/.ssh/id_rsa
    owner: kris
    group: kris
    mode: 0600
  no_log: true
  tags:
    - ssh
    - kris
  when:
    - ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    - inventory_hostname == "titanium"
