---

- name: Create user account - Kris
  user:
    comment: Kristopher Newman
    name: kris
    password: "{{ kris_pw_hash }}"
    append: yes
    groups:
     - sudo
     - adm
     - cdrom
     - sudo
     - dip
     - plugdev
     - lpadmin
     - sambashare
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/kris
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Deploy SSH key for kris from github
  authorized_key:
    user: kris
    key: "https://github.com/khaosx.keys"

- name: Add Kris user to the sudoers
  copy:
    dest: "/etc/sudoers.d/kris"
    content: "kris  ALL=(ALL)  NOPASSWD: ALL"

- name: Create user account - Plex
  user:
    comment: Plex User
    name: plex
    password: "{{ plex_pw_hash }}"
    append: yes
    groups:
      - cdrom
      - dip
      - plugdev
      - lpadmin
      - sambashare
    state: present
    shell: /bin/bash
    system: no
    createhome: yes
    home: /home/plex
  tags:
    - useradd
    - plex
  when: "'plex' in group_names"

- name: Create user account - pihole
  user:
    comment: "Pihole NoLogin user"
    name: pihole
    append: yes
    groups:
     - www-data
    state: present
    shell: /sbin/nologin
    system: no
    createhome: yes
    uid: 999
  tags:
    - useradd
    - pihole
  when: "'pihole_vm' in group_names"