---
- name: Install MySQL
  apt:
    pkg:
      - mysql-server-core-5.7
      - mysql-client-core-5.7
      - libmysqlclient-dev
      - mysql-server
      - mysql-client
      - python3-pymysql
    state: present
  tags:
  - mysql

- name: Copy .my.cnf file with root password credentials
  template:
    src: templates/.root.cnf
    dest: /etc/mysql/my.cnf
    owner: root
    mode: 0600
  tags:
  - mysql

- name: Copy .my.cnf file with root password credentials
  template:
    src: templates/.root.cnf
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  tags:
  - mysql

- name: Copy .my.cnf file with root password credentials
  template:
    src: templates/.jarvis.cnf
    dest: /home/jarvis/.my.cnf
    owner: jarvis
    mode: 0600
  tags:
  - mysql

- name: Update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  no_log: true
  tags:
  - mysql

- name: Start mysql
  service:
    name=mysql
    enabled=yes
    state=started
  tags:
  - mysql

- name: Remove the test database
  mysql_db:
    name: test
    state: absent
  tags:
  - mysql

- name: Create deploy user for mysql
  mysql_user:
    name: jarvis
    host: "%"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
  no_log: true
  tags:
  - mysql

- name: Ensure anonymous users are not in the database
  mysql_user:
    user: ''
    host: "{{ item }}"
    state: absent
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  no_log: true
  tags:
  - mysql
